title = "Imaging the neural systems underlying human communication"
tag = "AuditoryImaging_USC_01_14_2026"
base_url = "http://sitek.github.io"
remote = "git@github.com:sitek/sitek-communication-neuroscience.git"
talk_url = "http://sitek.github.io/sitek-communication-neuroscience/talk/talk.html"
repo_url = "http://sitek.github.io/sitek-communication-neuroscience"
